Added network stats
criteo/babar pull request #14
Opened 2018-06-14 08:00 UTC by essigt

Added stats from /proc/net/dev

![image](https://user-images.githubusercontent.com/464332/41399065-9c95d5bc-6fb9-11e8-848a-076bfcbf407f.png)

2018-06-15 08:54 UTC, BenoitHanotte commented
Hello @essigt, thanks for your PR, this has been on my todo list for some time but I never got around to work on it :)
My only concern about it is that, as far as I know, there is no way to get network usage for the process tree only and we can only get it for the entire host? (it is not an issue, I would just make sure that it is clearly stated and differentiated from the IO graphs that show the usage only on the process tree). Also, is there a risk of capturing local/virtual network interfaces that could make the result invalid?
I will run some tests today or early next week to make sure it works on our infra and then we should be able to merge :)

2018-06-21 16:56 UTC, essigt commented
Hello @BenoitHanotte I committed a change to only take non-virtual interfaces into account and also stated the fact more clearly that the graph shows the IO from the entire host.

2018-06-27 12:18 UTC, BenoitHanotte requested changes
Looks good, there are only a few minor comments :+1:

2018-06-27 12:18 UTC, BenoitHanotte commented on babar-agent/src/main/java/com/criteo/babar/agent/profiler/utils/ProcFSUtils.java
> +		List<String> realDevices = new LinkedList<>();
I see that we then check for a device using `contains()`, for this reason I would avoid using a `LinkedList` and instead use an `ArrayList` (which will be better for cache locality and will avoid having to allocate an iterator to go through the list).
Even better, as we will usually have more than a 2-3 devices, we could use a `HashSet` to allow searching in `O(1)`

2018-06-27 12:18 UTC, BenoitHanotte commented on babar-agent/src/main/java/com/criteo/babar/agent/profiler/utils/ProcFSUtils.java
> +				if(!cols[10].startsWith("../../devices/virtual/net/")) {
the two `if`s could be factorized as
`if (cols.length == 11 && !cols[10].startsWith("../../devices/virtual/net/")`

2018-06-27 12:18 UTC, BenoitHanotte commented on babar-report/src/IO.vue
> +          This graph shows the total number of bytes of data transmitted or received by all non-virtual interfaces by the entire process-tree as reported by the <kbd>/prod/net/dev</kbd> file.<br>
There's a typo, it's `/proc`. I have made that typo everywhere else, I'll push a PR to fix the other ones ;)

2018-06-27 12:29 UTC, BenoitHanotte commented
I was also wondering whether we wanted to show both the median and max network usage instead of only the maximum one that I believe is currently shown?
But that can be adjusted later so no worries

2018-06-29 12:03 UTC, essigt commented
Hey @BenoitHanotte thanks for the great feedback :)
I try to add the changes in the next days.

2018-07-04 07:13 UTC, BenoitHanotte commented on babar-report/src/IO.vue
> +          This graph shows the total number of bytes of data transmitted or received by all non-virtual interfaces by the entire process-tree as reported by the <kbd>/proc/net/dev</kbd> file.<br>
I may have missed this one on the first pass, but if I am not mistaken it is not the network usage of the process tree but the one of the entire system (the host OS)?

2018-07-17 07:28 UTC, essigt commented on babar-report/src/IO.vue
> +          This graph shows the total number of bytes of data transmitted or received by all non-virtual interfaces by the entire process-tree as reported by the <kbd>/proc/net/dev</kbd> file.<br>
Yes of course, it is the network usage of the entire system

2018-07-23 06:38 UTC, BenoitHanotte approved these changes

2018-07-23 06:38 UTC, BenoitHanotte commented
@essigt Thanks a lot for the PR, I am merging it right now :)

2018-07-23 06:38 UTC, merged